"sample_annotation" : {
    "imgWidth": 2048,
    "imgHeight": 1024,
    "sensor": {
        "sensor_T_ISO_8855": [
            [
                0.9990881051503779,
                -0.01948468779721943,
                -0.03799085532693703,
                -1.6501524664770573
            ],
            [
                0.019498764210995674,
                0.9998098810245096,
                0.0,
                -0.1331288872611436
            ],
            [
                0.03798363254444427,
                -0.0007407747301939942,
                0.9992780868764849,
                -1.2836173638418473
            ]
        ],
        "fx": 2262.52,
        "fy": 2265.3017905988554,
        "u0": 1096.98,
        "v0": 513.137,
        "baseline": 0.209313
    },
    "objects": [
        {
            "2d": {
                "modal": [
                    609,
                    420,
                    198,
                    111
                ],
                "amodal": [
                    602,
                    415,
                    214,
                    118
                ]
            },
            "3d": {
                "center": [
                    33.95,
                    5.05,
                    0.57
                ],
                "dimensions": [
                    4.3,
                    1.72,
                    1.53
                ],
                "rotation": [
                    0.9735839424380041,
                    -0.010751769161021867,
                    0.0027191710555974913,
                    0.22805988817753894
                ],
                "type": "Mid Size Car",
                "format": "CRS_ISO8855"
            },
            "occlusion": 0.0,
            "truncation": 0.0,
            "instanceId": 26010,
            "label": "car",
            "score": 1.0
        }
    ]
}
